apiVersion: argoproj.io/v1alpha1     
kind: Rollout  
metadata:
  name: rollout-bluegreen
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:rollout.argoproj.io/revision': {}
        'f:spec':
          'f:replicas': {}
          'f:template':
            'f:spec':
              'f:containers': {}
              'f:initContainers': {}
        ...
      manager: rollouts-controller
      operation: Update
      time: '2022-01-13T05:10:02Z'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        #image: argoproj/rollouts-demo:blue
        # image: argoproj/rollouts-demo:green
        image: argoproj/rollouts-demo:yellow
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active 
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
